// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhjTinRp_odexEo3KMUfqDYeTM-DsJgYA',
    appId: '1:157887385638:web:34a94022913c29734296e7',
    messagingSenderId: '157887385638',
    projectId: 'econance-e81ec',
    authDomain: 'econance-e81ec.firebaseapp.com',
    storageBucket: 'econance-e81ec.firebasestorage.app',
    measurementId: 'G-ZGTFLVLXBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMI81U4s7ckfOr9Dp3H4tgYymikyvZXhE',
    appId: '1:157887385638:android:bd9b75f14e3a19444296e7',
    messagingSenderId: '157887385638',
    projectId: 'econance-e81ec',
    storageBucket: 'econance-e81ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBuZC1o1tMoD9AbeIMXYFBNf89tpL9GDU',
    appId: '1:157887385638:ios:5ec120b1a98240eb4296e7',
    messagingSenderId: '157887385638',
    projectId: 'econance-e81ec',
    storageBucket: 'econance-e81ec.firebasestorage.app',
    iosBundleId: 'com.example.econance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBuZC1o1tMoD9AbeIMXYFBNf89tpL9GDU',
    appId: '1:157887385638:ios:5ec120b1a98240eb4296e7',
    messagingSenderId: '157887385638',
    projectId: 'econance-e81ec',
    storageBucket: 'econance-e81ec.firebasestorage.app',
    iosBundleId: 'com.example.econance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhjTinRp_odexEo3KMUfqDYeTM-DsJgYA',
    appId: '1:157887385638:web:80067ac5ba3e5d3f4296e7',
    messagingSenderId: '157887385638',
    projectId: 'econance-e81ec',
    authDomain: 'econance-e81ec.firebaseapp.com',
    storageBucket: 'econance-e81ec.firebasestorage.app',
    measurementId: 'G-1PLEWP9C3N',
  );
}
